### ISSUE TITLE
1617velv-calaf2m1 is a duplicate

### ISSUE THREAD

**Issue by sungjuchoi** [cheer4ftc/ftc-data#4]
Found another error in cala. 1617velv-calaf2m1 is a duplicate of 1617velv-calaf1m2. I believe calaf2m1 is the wrong one.

Thanks

**Comment by cheer4ftc** [comment]
Thanks again. 

Fixing this one is a little tougher. I'm getting the data from the matches.txt file in the scoring software output zip files provided by LA FTC here: https://drive.google.com/drive/folders/0B19hbGqI7-ziaEZPUHpybHA4bWs

The problem here is that for the F2 meet 1 zip file, there is no matches.txt file(!!!). This means that I don't have access to the detailed match results for this meet. The zip file does have the non-detailed MatchResults file that I can use, so I'll try to put that info up. However, the results will look different (without breakdowns for auton, teleop, end, etc.) because of the lack of data.

I'll close this out once I've updated these results.

**Comment by cheer4ftc** [comment]
Correct results for CALA F2M1 have now been uploaded. As noted before, no details are available so the results files for this meet differ from all of the other CALA meets. :(
